#       ,gggg,
#     ,88"""Y8b,
#    d8"     `Y8
#   d8'   8b  d8
#  ,8I    "Y88P'
#  I8'             ,gg,   ,gg
#  d8             d8""8b,dP"
#  Y8,           dP   ,88"
#  `Yba,,_____,,dP  ,dP"Y8,
#   `"Y88888888"  dP"   "Y8
#         [By Enttbot].
#
#        CONFIG.YML (v2.2)

################################################################
#                                                              #
#                        Placeholders :                        #
#  ---------------------------------------------------------   #
#  |   %cx_prefix%      : Plugin prefix                    |   #
#  |   %cx_clan_leader% : Clan leader's name               |   #
#  |   %cx_clan_founder% : Clan founder's name             |   #
#  |   %cx_clan_name%   : Clan's name                      |   #
#  |   %cx_clan_money%   : See the money vault of the clan |   #
#  |   %cx_clan_membercount_offline% : Members offline     |   #
#  |   %cx_clan_membercount_online% : Members online       |   #
#  |   %cx_clan_membercount% : Number of clan members      |   #
#  |   %cx_player_money% : The money vault of the player   |   #
#  ---------------------------------------------------------   #
#        Now you can use PlaceholderAPIÂ´s placeholders.        #
#                                                              #
################################################################

prefix: "&3&L[Clans&b&lX&3&l]: "

welcome-message:
  enabled: true

  no-clan:
    - "&f--------------------------------"
    - "&eWelcome back!"
    - "&7Use &a/cl create &7to create your clan."
    - "&f--------------------------------"

  self-clan:
    - "&f--------------------------------"
    - "&eYou are in clan &a%cx_clan_name%"
    - "&7Online members: &a%cx_clan_membercount_online%&7/&f%cx_clan_membercount%"
    - "&f--------------------------------"

  to-clan:
    - "&f--------------------------------"
    - "&a%player_name% &7from the clan has joined the server"
    - "&f--------------------------------"

max-clans: 50 # 0 = unlimited

economy:
  enabled: true
  system: "Vault" # Vault / Internal (ClansX economy system)

  cost:
    create-clan: 5
  earn:
    delete-clan: 1
    kill-enemy: 2.5

names-blocked:
  # Put here the names that you do not accept for a clan.
  enabled: true
  blocked:
    - "shit"
    - "fuck"
    - "nigga"
    - "KKK"