#       ,gggg,
#     ,88"""Y8b,
#    d8"     `Y8
#   d8'   8b  d8
#  ,8I    "Y88P'
#  I8'             ,gg,   ,gg
#  d8             d8""8b,dP"
#  Y8,           dP   ,88"
#  `Yba,,_____,,dP  ,dP"Y8,
#   `"Y88888888"  dP"   "Y8
#         [By Enttbot].
#
#        CONFIG.YML (v2)

################################################################
#                                                              #
#                        Placeholders :                        #
#  ---------------------------------------------------------   #
#  |   %cx_prefix%      : Plugin prefix                    |   #
#  |   %cx_clan_leader% : Clan leader's name               |   #
#  |   %cx_clan_membercount% : Number of clan members      |   #
#  |   %cx_clan_founder% : Clan founder's name             |   #
#  |   %cx_clan_name%   : Clan's name                      |   #
#  ---------------------------------------------------------   #
#        Now you can use PlaceholderAPIÂ´s placeholders.        #
#                                                              #
################################################################

prefix: "&3&L[Clans&b&lX&3&l]: "

welcome-message:
  enabled: true
  message:
    - "&f--------------------------------"
    - " "
    - "&e&lA player from your clan %cx_clan_name% has joined"
    - "&e&lGreeting to player %player_name%"
    - "&2&lMessage by %cx_prefix%"
    - " "
    - "&f--------------------------------"

# This is required and should not be set to 0
# If you write 0 in all values, the interaction with the vault is converted to 0, that is, it will say something like this:
# [ClansX] you successfully created clan %cx.clan.name% [cost].
vault-integration:
  enabled: true

  cost:
    create-clan: 5 # always up to 0
  earn:
    delete-clan: 1 # always up to 0
    kill-enemy: 2.5 # always up to 0

names-blocked:
  # Put here the names that you do not accept for a clan.
  enabled: true
  blocked:
    - "shit"
    - "fuck"
    - "nigga"